name: Deploy Storybook Docs
run-name: ${{github.actor}} is deploying the storybook.

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Job to build and deploy the storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.JS Version 18 LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: run npm run build with turbo token cache from vercel
        run: npm run build
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN_VERCEL }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM_VERCEL }}

      - name: Deploy Storybook Design System KENAIFIRE-UI to Github Pages
        working-directory: ./packages/docs
        run: touch storybook-static/.nojekyll && npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
